// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/kstackhq/kstack/sidecar/internal/apimeta"
	"github.com/kstackhq/kstack/sidecar/internal/llm"
	"github.com/kstackhq/kstack/sidecar/internal/memorysvc"
)

// The connecting principal's effective RBAC in one namespace (live
// SelfSubjectRulesReview). Namespace-scoped (the API has no all-namespaces form)
// and point-in-time — for UI/debugging, not authoritative for access decisions.
type ClusterPermissions struct {
	// The namespace these rules were evaluated for.
	Namespace string `json:"namespace"`
	// Allowed resource rules (verbs × apiGroups × resources).
	ResourceRules []*ResourceRule `json:"resourceRules"`
	// Allowed non-resource rules (verbs × URLs), e.g. /healthz.
	NonResourceRules []*NonResourceRule `json:"nonResourceRules"`
	// True if some authorizers couldn't be evaluated, so the rule set may be incomplete.
	Incomplete bool `json:"incomplete"`
}

type MemorySaveInput struct {
	// The memory to rewrite. Null creates one.
	ID *memorysvc.MemoryID `json:"id,omitempty"`
	// The cluster it is for. Null is every cluster.
	ClusterID *apimeta.ClusterID `json:"clusterID,omitempty"`
	Name      string             `json:"name"`
	Body      string             `json:"body"`
}

// A model the sidecar can answer with.
type Model struct {
	Provider *Provider `json:"provider"`
	ID       string    `json:"id"`
	Label    string    `json:"label"`
	// The effort levels this model accepts, in the provider's own words, least to most. Empty when it has no such knob.
	Efforts []string `json:"efforts"`
	// The level a picker starts on. Empty when `efforts` is.
	DefaultEffort string `json:"defaultEffort"`
}

type Mutation struct {
}

// A non-resource RBAC rule: the verbs the principal may use against non-resource URLs (e.g. /healthz).
type NonResourceRule struct {
	Verbs           []string `json:"verbs"`
	NonResourceUrls []string `json:"nonResourceUrls"`
}

// A provider the sidecar can send a turn to.
type Provider struct {
	// Stable for the life of the app: what `chatSend` and a stored message name.
	ID string `json:"id"`
	// What a picker shows as the group heading.
	Label string `json:"label"`
	// The dialect this provider speaks. Null on a provider the sidecar no longer holds — a stored message's, labelled by its id — since nothing but the id is known of it.
	LlmDialect *llm.Dialect `json:"llmDialect,omitempty"`
}

type Query struct {
}

// A resource-scoped RBAC rule: the verbs the principal may use on the given apiGroups/resources (optionally narrowed to named instances).
type ResourceRule struct {
	Verbs     []string `json:"verbs"`
	APIGroups []string `json:"apiGroups"`
	Resources []string `json:"resources"`
	// Specific resource names this rule is restricted to; empty means all.
	ResourceNames []string `json:"resourceNames"`
}

type Subscription struct {
}
